### ISSUE TITLE
Dumper usage demo error

### ISSUE THREAD

**Issue by Siceberg** [Phynix/yamlloader#8] opened 2018-02-08 10:10 UTC
I am a python beginner, I used [Dumper usage demo](https://github.com/Phynix/yamlloader#dumper-usage) and got error:

Traceback (most recent call last):
  File "test1.py", line 7, in <module>
    import yamlloader
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yamlloader/__init__.py", line 12, in <module>
    from . import ordereddict
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yamlloader/ordereddict/__init__.py", line 5, in <module>
    from .loaders import Loader, SafeLoader, CLoader, CSafeLoader
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yamlloader/ordereddict/loaders.py", line 59, in <module>
    class CLoader(OrderedLoaderMixin, yaml.CLoader):
AttributeError: module 'yaml' has no attribute 'CLoader'

How can I handle this error?

**Comment by mayou36** [comment] 2018-02-08 14:05
This happens if pyyaml did not "install" correctly and the C-versions of loaders and dumpers are not available.

How did you install pyyaml? With pip? Or conda?

We are further aware of the issue and a release (which even works if pyyaml did not compile correctly) will be released very shortly.

**Comment by mayou36** [comment] 2018-02-08 14:52
A new version has been release fixing this issue. It will shortly be available on pip and later on also on Anaconda (depending how you install yamlloader).
Let me know if the problem is solved

**Comment by Siceberg** [comment] 2018-02-09 02:30
Thank for your job, I tried the new version (yamlloader-0.5.2), the code is working.

PS:
I install pyyaml by pip3, How to determine whether the installation is correct?

**Closed** 2018-02-09 02:57 UTC
Labels: bug
